In [1]:
import pandas as pd
import os

# Step 1: Specify the file path
file_path = '/content/bank-additional-full.csv'  # Replace with your actual file path

# Step 2: Load the dataset with error handling
try:
    # Read the CSV file, handle bad lines, and remove quotes
    df = pd.read_csv(
        file_path,
        sep=';',
        header=0,
        on_bad_lines='skip',
        quotechar='"',
        engine='python'
    )

    # Step 3: Clean column names (remove leading/trailing whitespaces)
    df.columns = [col.strip() for col in df.columns]

    # Step 4: Remove quotes from string values and clean the data
    for col in df.select_dtypes(include=['object']).columns:
        df[col] = df[col].str.replace('"', '', regex=False).str.strip()

    # Step 5: Save the cleaned dataset as a new CSV file in the current directory
    output_file = os.path.join(os.getcwd(), 'bank_additional_full_dataset.csv')  # Save in the current directory
    df.to_csv(output_file, index=False)

    print(f"Cleaned dataset saved as: {output_file}")

except Exception as e:
    print(f"An error occurred: {e}")

Cleaned dataset saved as: /content/bank_additional_full_dataset.csv

In [2]:
# Step 1: Revert to Compatible Versions of Libraries
!pip install numpy==1.26.4 pandas==2.2.2 tensorflow==2.17.1 scikit-learn matplotlib seaborn

# Step 2: Verify Installed Versions
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib

print(f"Numpy version: {np.__version__}")
print(f"Pandas version: {pd.__version__}")
print(f"TensorFlow version: {tf.__version__}")
print(f"Matplotlib version: {matplotlib.__version__}")


# Step 3: Suppress Future Warnings
import warnings
warnings.filterwarnings("ignore")

Requirement already satisfied: numpy==1.26.4 in /usr/local/lib/python3.10/dist-packages (1.26.4)
Requirement already satisfied: pandas==2.2.2 in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: tensorflow==2.17.1 in /usr/local/lib/python3.10/dist-packages (2.17.1)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.6.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (3.8.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.10/dist-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas==2.2.2) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas==2.2.2) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas==2.2.2) (2024.2)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.17.1) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.17.1) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.17.1) (24.3.25)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.17.1) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.17.1) (0.2.0)
Requirement already satisfied: h5py>=3.10.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.17.1) (3.12.1)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.17.1) (18.1.1)
Requirement already satisfied: ml-dtypes<0.5.0,>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.17.1) (0.4.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.17.1) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.17.1) (24.2)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.17.1) (4.25.5)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.17.1) (2.32.3)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.17.1) (75.1.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.17.1) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.17.1) (2.5.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.17.1) (4.12.2)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.17.1) (1.17.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.17.1) (1.68.1)
Requirement already satisfied: tensorboard<2.18,>=2.17 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.17.1) (2.17.1)
Requirement already satisfied: keras>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.17.1) (3.5.0)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow==2.17.1) (0.37.1)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (4.55.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (1.4.7)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (11.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib) (3.2.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from astunparse>=1.6.0->tensorflow==2.17.1) (0.45.1)
Requirement already satisfied: rich in /usr/local/lib/python3.10/dist-packages (from keras>=3.2.0->tensorflow==2.17.1) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.10/dist-packages (from keras>=3.2.0->tensorflow==2.17.1) (0.0.8)
Requirement already satisfied: optree in /usr/local/lib/python3.10/dist-packages (from keras>=3.2.0->tensorflow==2.17.1) (0.13.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorflow==2.17.1) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorflow==2.17.1) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorflow==2.17.1) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorflow==2.17.1) (2024.12.14)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.18,>=2.17->tensorflow==2.17.1) (3.7)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.18,>=2.17->tensorflow==2.17.1) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from tensorboard<2.18,>=2.17->tensorflow==2.17.1) (3.1.3)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.10/dist-packages (from werkzeug>=1.0.1->tensorboard<2.18,>=2.17->tensorflow==2.17.1) (3.0.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich->keras>=3.2.0->tensorflow==2.17.1) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich->keras>=3.2.0->tensorflow==2.17.1) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.2.0->tensorflow==2.17.1) (0.1.2)
Numpy version: 1.26.4
Pandas version: 2.2.2
TensorFlow version: 2.17.1
Matplotlib version: 3.8.0

## Try to see How many numerical features

In [3]:
# Load the dataset (replace 'file.csv' with your dataset file)
df = pd.read_csv('/content/bank_additional_full_dataset.csv')

# Check data types
print("Data Types:\n", df.dtypes)

# Extract numerical columns
numerical_features = df.select_dtypes(include=['int64', 'float64']).columns
print("\nNumerical Features:\n", numerical_features)

# Summary statistics for numerical features
print("\nSummary Statistics for Numerical Features:\n", df[numerical_features].describe())

Data Types:
 age                 int64
job                object
marital            object
education          object
default            object
housing            object
loan               object
contact            object
month              object
day_of_week        object
duration            int64
campaign            int64
pdays               int64
previous            int64
poutcome           object
emp.var.rate      float64
cons.price.idx    float64
cons.conf.idx     float64
euribor3m         float64
nr.employed       float64
y                  object
dtype: object

Numerical Features:
 Index(['age', 'duration', 'campaign', 'pdays', 'previous', 'emp.var.rate',
       'cons.price.idx', 'cons.conf.idx', 'euribor3m', 'nr.employed'],
      dtype='object')

Summary Statistics for Numerical Features:
                age      duration      campaign         pdays      previous  \
count  41188.00000  41188.000000  41188.000000  41188.000000  41188.000000
mean      40.02406    258.285010      2.567593    962.475454      0.172963
std       10.42125    259.279249      2.770014    186.910907      0.494901
min       17.00000      0.000000      1.000000      0.000000      0.000000
25%       32.00000    102.000000      1.000000    999.000000      0.000000
50%       38.00000    180.000000      2.000000    999.000000      0.000000
75%       47.00000    319.000000      3.000000    999.000000      0.000000
max       98.00000   4918.000000     56.000000    999.000000      7.000000

       emp.var.rate  cons.price.idx  cons.conf.idx     euribor3m   nr.employed
count  41188.000000    41188.000000   41188.000000  41188.000000  41188.000000
mean       0.081886       93.575664     -40.502600      3.621291   5167.035911
std        1.570960        0.578840       4.628198      1.734447     72.251528
min       -3.400000       92.201000     -50.800000      0.634000   4963.600000
25%       -1.800000       93.075000     -42.700000      1.344000   5099.100000
50%        1.100000       93.749000     -41.800000      4.857000   5191.000000
75%        1.400000       93.994000     -36.400000      4.961000   5228.100000
max        1.400000       94.767000     -26.900000      5.045000   5228.100000

# Try to see How many categorical features

In [4]:
# Extract categorical columns
categorical_features = df.select_dtypes(include=['object', 'category']).columns
print("\nCategorical Features:\n", categorical_features)


# Analyze each categorical feature
for feature in categorical_features:
    print(f"\nFeature: {feature}")
    print(f"Unique Values: {df[feature].nunique()}")
    print(f"Most Frequent Categories:\n{df[feature].value_counts().head()}")

Categorical Features:
 Index(['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact',
       'month', 'day_of_week', 'poutcome', 'y'],
      dtype='object')

Feature: job
Unique Values: 12
Most Frequent Categories:
job
admin.         10422
blue-collar     9254
technician      6743
services        3969
management      2924
Name: count, dtype: int64

Feature: marital
Unique Values: 4
Most Frequent Categories:
marital
married     24928
single      11568
divorced     4612
unknown        80
Name: count, dtype: int64

Feature: education
Unique Values: 8
Most Frequent Categories:
education
university.degree      12168
high.school             9515
basic.9y                6045
professional.course     5243
basic.4y                4176
Name: count, dtype: int64

Feature: default
Unique Values: 3
Most Frequent Categories:
default
no         32588
unknown     8597
yes            3
Name: count, dtype: int64

Feature: housing
Unique Values: 3
Most Frequent Categories:
housing
yes        21576
no         18622
unknown      990
Name: count, dtype: int64

Feature: loan
Unique Values: 3
Most Frequent Categories:
loan
no         33950
yes         6248
unknown      990
Name: count, dtype: int64

Feature: contact
Unique Values: 2
Most Frequent Categories:
contact
cellular     26144
telephone    15044
Name: count, dtype: int64

Feature: month
Unique Values: 10
Most Frequent Categories:
month
may    13769
jul     7174
aug     6178
jun     5318
nov     4101
Name: count, dtype: int64

Feature: day_of_week
Unique Values: 5
Most Frequent Categories:
day_of_week
thu    8623
mon    8514
wed    8134
tue    8090
fri    7827
Name: count, dtype: int64

Feature: poutcome
Unique Values: 3
Most Frequent Categories:
poutcome
nonexistent    35563
failure         4252
success         1373
Name: count, dtype: int64

Feature: y
Unique Values: 2
Most Frequent Categories:
y
no     36548
yes     4640
Name: count, dtype: int64

# Check Missing Values

In [5]:
import pandas as pd

# Step 1: Load the dataset
file_path = "/content/bank_additional_full_dataset.csv"  # Update this with the path to your CSV file
df = pd.read_csv(file_path)

# Step 2: Check for missing values
missing_values = df.isnull().sum()
print("\nMissing Values:\n", missing_values)

Missing Values:
 age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
dtype: int64

# Detect Outliers of numerical features

In [6]:
from scipy.stats import zscore

# Calculate Z-scores for each numerical feature
z_scores = df[numerical_features].apply(zscore)

# Define a threshold (commonly 3 or -3)
threshold = 3

# Detect outliers (absolute Z-score greater than the threshold)
outliers = (z_scores.abs() > threshold)

# Print outliers for each feature
for feature in numerical_features:
    print(f"\nOutliers for feature '{feature}':")
    print(df[outliers[feature]])

Outliers for feature 'age':
       age      job   marital            education  default housing loan  \
27757   76  retired   married    university.degree       no      no  yes
27780   73  retired   married    university.degree       no     yes   no
27800   88  retired  divorced             basic.4y       no     yes   no
27802   88  retired  divorced             basic.4y       no      no   no
27805   88  retired  divorced             basic.4y       no     yes  yes
...    ...      ...       ...                  ...      ...     ...  ...
40986   84  retired  divorced             basic.4y  unknown     yes  yes
40996   81  retired   married             basic.4y       no     yes   no
41004   80  retired   married  professional.course       no     yes   no
41183   73  retired   married  professional.course       no     yes   no
41187   74  retired   married  professional.course       no     yes   no

        contact month day_of_week  ...  campaign  pdays  previous  \
27757  cellular   mar         thu  ...         9    999         0
27780  cellular   mar         tue  ...         1    999         1
27800  cellular   mar         wed  ...         1    999         0
27802  cellular   mar         wed  ...         2    999         0
27805  cellular   mar         wed  ...         5    999         0
...         ...   ...         ...  ...       ...    ...       ...
40986  cellular   oct         mon  ...         4      3         1
40996  cellular   oct         wed  ...         1    999         2
41004  cellular   oct         thu  ...         1    999         1
41183  cellular   nov         fri  ...         1    999         0
41187  cellular   nov         fri  ...         3    999         1

          poutcome emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
27757  nonexistent         -1.8          92.843          -50.0      1.757
27780      failure         -1.8          92.843          -50.0      1.687
27800  nonexistent         -1.8          92.843          -50.0      1.663
27802  nonexistent         -1.8          92.843          -50.0      1.663
27805  nonexistent         -1.8          92.843          -50.0      1.663
...            ...          ...             ...            ...        ...
40986      success         -1.1          94.601          -49.5      1.000
40996      failure         -1.1          94.601          -49.5      1.016
41004      failure         -1.1          94.601          -49.5      1.025
41183  nonexistent         -1.1          94.767          -50.8      1.028
41187      failure         -1.1          94.767          -50.8      1.028

       nr.employed    y
27757       5099.1   no
27780       5099.1   no
27800       5099.1   no
27802       5099.1  yes
27805       5099.1  yes
...            ...  ...
40986       4963.6   no
40996       4963.6  yes
41004       4963.6  yes
41183       4963.6  yes
41187       4963.6   no

[369 rows x 21 columns]

Outliers for feature 'duration':
       age           job   marital            education  default housing loan  \
37      52    technician   married             basic.9y       no     yes   no
75      41   blue-collar  divorced             basic.4y  unknown     yes   no
83      49  entrepreneur   married    university.degree  unknown     yes   no
88      49    technician   married             basic.9y       no      no   no
164     39      services  divorced          high.school  unknown      no   no
...    ...           ...       ...                  ...      ...     ...  ...
40880   28        admin.    single          high.school       no      no   no
40970   24        admin.    single    university.degree       no     yes   no
41121   46        admin.    single    university.degree       no     yes   no
41123   36   blue-collar    single             basic.6y       no      no   no
41164   54        admin.   married  professional.course       no      no   no

         contact month day_of_week  ...  campaign  pdays  previous  \
37     telephone   may         mon  ...         1    999         0
75     telephone   may         mon  ...         1    999         0
83     telephone   may         mon  ...         1    999         0
88     telephone   may         mon  ...         1    999         0
164    telephone   may         mon  ...         1    999         0
...          ...   ...         ...  ...       ...    ...       ...
40880   cellular   oct         wed  ...         2    999         0
40970   cellular   oct         fri  ...         3      3         2
41121   cellular   nov         tue  ...         3    999         1
41123   cellular   nov         tue  ...         4    999         0
41164   cellular   nov         tue  ...         2     10         1

          poutcome emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
37     nonexistent          1.1          93.994          -36.4      4.857
75     nonexistent          1.1          93.994          -36.4      4.857
83     nonexistent          1.1          93.994          -36.4      4.857
88     nonexistent          1.1          93.994          -36.4      4.857
164    nonexistent          1.1          93.994          -36.4      4.857
...            ...          ...             ...            ...        ...
40880  nonexistent         -1.1          94.601          -49.5      0.959
40970      success         -1.1          94.601          -49.5      0.993
41121      failure         -1.1          94.767          -50.8      1.046
41123  nonexistent         -1.1          94.767          -50.8      1.046
41164      success         -1.1          94.767          -50.8      1.035

       nr.employed    y
37          5191.0   no
75          5191.0  yes
83          5191.0  yes
88          5191.0  yes
164         5191.0   no
...            ...  ...
40880       4963.6  yes
40970       4963.6  yes
41121       4963.6   no
41123       4963.6  yes
41164       4963.6  yes

[861 rows x 21 columns]

Outliers for feature 'campaign':
       age          job   marital            education  default housing loan  \
2189    56       admin.   married             basic.9y  unknown      no   no
2234    47   management   married    university.degree       no      no   no
2554    31       admin.   married          high.school  unknown     yes   no
2589    47     services   married          high.school  unknown      no  yes
2590    47  blue-collar   married  professional.course  unknown     yes   no
...    ...          ...       ...                  ...      ...     ...  ...
37587   28   unemployed   married  professional.course       no      no   no
37876   29       admin.    single    university.degree       no     yes  yes
37893   52       admin.   married              unknown       no      no   no
40063   21      student    single              unknown       no     yes  yes
40529   72      retired  divorced    university.degree       no      no   no

         contact month day_of_week  ...  campaign  pdays  previous  \
2189   telephone   may         mon  ...        11    999         0
2234   telephone   may         mon  ...        12    999         0
2554   telephone   may         tue  ...        13    999         0
2589   telephone   may         tue  ...        11    999         0
2590   telephone   may         tue  ...        11    999         0
...          ...   ...         ...  ...       ...    ...       ...
37587  telephone   aug         fri  ...        11    999         0
37876   cellular   aug         mon  ...        12    999         0
37893  telephone   sep         tue  ...        13     14         2
40063   cellular   jul         thu  ...        11      9         2
40529   cellular   aug         mon  ...        16    999         1

          poutcome emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
2189   nonexistent          1.1          93.994          -36.4      4.857
2234   nonexistent          1.1          93.994          -36.4      4.857
2554   nonexistent          1.1          93.994          -36.4      4.856
2589   nonexistent          1.1          93.994          -36.4      4.856
2590   nonexistent          1.1          93.994          -36.4      4.856
...            ...          ...             ...            ...        ...
37587  nonexistent         -2.9          92.201          -31.4      0.869
37876  nonexistent         -2.9          92.201          -31.4      0.821
37893      failure         -3.4          92.379          -29.8      0.819
40063      failure         -1.7          94.215          -40.3      0.810
40529      failure         -1.7          94.027          -38.3      0.891

       nr.employed   y
2189        5191.0  no
2234        5191.0  no
2554        5191.0  no
2589        5191.0  no
2590        5191.0  no
...            ...  ..
37587       5076.2  no
37876       5076.2  no
37893       5017.5  no
40063       4991.6  no
40529       4991.6  no

[869 rows x 21 columns]

Outliers for feature 'pdays':
       age            job   marital            education  default housing  \
24108   37         admin.   married    university.degree       no     yes
24264   48     management   married    university.degree       no     yes
24279   42     technician   married  professional.course  unknown     yes
24397   50   entrepreneur   married    university.degree  unknown     yes
24482   36  self-employed    single    university.degree       no     yes
...    ...            ...       ...                  ...      ...     ...
41163   35     technician  divorced             basic.4y       no     yes
41164   54         admin.   married  professional.course       no      no
41174   62        retired   married    university.degree       no     yes
41178   62        retired   married    university.degree       no      no
41182   29     unemployed    single             basic.4y       no     yes

      loan    contact month day_of_week  ...  campaign  pdays  previous  \
24108   no  telephone   nov         wed  ...         1      6         1
24264   no   cellular   nov         mon  ...         1      4         1
24279   no   cellular   nov         mon  ...         1      4         1
24397   no   cellular   nov         mon  ...         1      3         1
24482   no   cellular   nov         mon  ...         2      4         1
...    ...        ...   ...         ...  ...       ...    ...       ...
41163   no   cellular   nov         tue  ...         3      4         2
41164   no   cellular   nov         tue  ...         2     10         1
41174   no   cellular   nov         thu  ...         1      1         6
41178   no   cellular   nov         thu  ...         2      6         3
41182   no   cellular   nov         fri  ...         1      9         1

       poutcome emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  \
24108   success         -0.1          93.200          -42.0      4.286
24264   success         -0.1          93.200          -42.0      4.191
24279   success         -0.1          93.200          -42.0      4.191
24397   success         -0.1          93.200          -42.0      4.191
24482   success         -0.1          93.200          -42.0      4.191
...         ...          ...             ...            ...        ...
41163   success         -1.1          94.767          -50.8      1.035
41164   success         -1.1          94.767          -50.8      1.035
41174   success         -1.1          94.767          -50.8      1.031
41178   success         -1.1          94.767          -50.8      1.031
41182   success         -1.1          94.767          -50.8      1.028

       nr.employed    y
24108       5195.8   no
24264       5195.8   no
24279       5195.8   no
24397       5195.8   no
24482       5195.8   no
...            ...  ...
41163       4963.6  yes
41164       4963.6  yes
41174       4963.6  yes
41178       4963.6  yes
41182       4963.6   no

[1515 rows x 21 columns]

Outliers for feature 'previous':
       age         job   marital          education default housing loan  \
25996   35  management   married  university.degree      no     yes  yes
27658   50      admin.  divorced  university.degree      no     yes   no
27778   38  technician   married  university.degree      no      no   no
27832   30     student    single        high.school      no      no   no
27991   29      admin.    single  university.degree      no     yes   no
...    ...         ...       ...                ...     ...     ...  ...
41170   40  management  divorced  university.degree      no     yes   no
41173   62     retired   married  university.degree      no     yes   no
41174   62     retired   married  university.degree      no     yes   no
41175   34     student    single            unknown      no     yes   no
41178   62     retired   married  university.degree      no      no   no

         contact month day_of_week  ...  campaign  pdays  previous  poutcome  \
25996  telephone   nov         wed  ...         3      0         2   success
27658   cellular   nov         fri  ...         3      1         2   success
27778   cellular   mar         tue  ...         2    999         2   failure
27832   cellular   mar         fri  ...         5     10         2   failure
27991   cellular   apr         wed  ...         1      5         2   success
...          ...   ...         ...  ...       ...    ...       ...       ...
41170   cellular   nov         wed  ...         2    999         4   failure
41173   cellular   nov         thu  ...         1    999         2   failure
41174   cellular   nov         thu  ...         1      1         6   success
41175   cellular   nov         thu  ...         1    999         2   failure
41178   cellular   nov         thu  ...         2      6         3   success

      emp.var.rate  cons.price.idx  cons.conf.idx  euribor3m  nr.employed    y
25996         -0.1          93.200          -42.0      4.120       5195.8   no
27658         -0.1          93.200          -42.0      4.021       5195.8   no
27778         -1.8          92.843          -50.0      1.687       5099.1  yes
27832         -1.8          92.843          -50.0      1.640       5099.1  yes
27991         -1.8          93.075          -47.1      1.498       5099.1   no
...            ...             ...            ...        ...          ...  ...
41170         -1.1          94.767          -50.8      1.030       4963.6   no
41173         -1.1          94.767          -50.8      1.031       4963.6  yes
41174         -1.1          94.767          -50.8      1.031       4963.6  yes
41175         -1.1          94.767          -50.8      1.031       4963.6   no
41178         -1.1          94.767          -50.8      1.031       4963.6  yes

[1064 rows x 21 columns]

Outliers for feature 'emp.var.rate':
Empty DataFrame
Columns: [age, job, marital, education, default, housing, loan, contact, month, day_of_week, duration, campaign, pdays, previous, poutcome, emp.var.rate, cons.price.idx, cons.conf.idx, euribor3m, nr.employed, y]
Index: []

[0 rows x 21 columns]

Outliers for feature 'cons.price.idx':
Empty DataFrame
Columns: [age, job, marital, education, default, housing, loan, contact, month, day_of_week, duration, campaign, pdays, previous, poutcome, emp.var.rate, cons.price.idx, cons.conf.idx, euribor3m, nr.employed, y]
Index: []

[0 rows x 21 columns]

Outliers for feature 'cons.conf.idx':
Empty DataFrame
Columns: [age, job, marital, education, default, housing, loan, contact, month, day_of_week, duration, campaign, pdays, previous, poutcome, emp.var.rate, cons.price.idx, cons.conf.idx, euribor3m, nr.employed, y]
Index: []

[0 rows x 21 columns]

Outliers for feature 'euribor3m':
Empty DataFrame
Columns: [age, job, marital, education, default, housing, loan, contact, month, day_of_week, duration, campaign, pdays, previous, poutcome, emp.var.rate, cons.price.idx, cons.conf.idx, euribor3m, nr.employed, y]
Index: []

[0 rows x 21 columns]

Outliers for feature 'nr.employed':
Empty DataFrame
Columns: [age, job, marital, education, default, housing, loan, contact, month, day_of_week, duration, campaign, pdays, previous, poutcome, emp.var.rate, cons.price.idx, cons.conf.idx, euribor3m, nr.employed, y]
Index: []

[0 rows x 21 columns]

# Remove Outliers of numerical features

In [7]:
import pandas as pd
from scipy.stats import zscore

# Assuming `df` is your dataframe and `numerical_features` contains the numerical columns.

# Function to remove outliers based on Z-scores
def remove_outliers(df, numerical_features, z_threshold=3):
    # Calculate Z-scores for each numerical feature
    z_scores = df[numerical_features].apply(zscore)

    # Detect outliers (absolute Z-score greater than the threshold)
    outliers_z = (z_scores.abs() > z_threshold)

    # Remove rows where any feature has an outlier
    df_cleaned = df[~outliers_z.any(axis=1)]

    return df_cleaned, outliers_z

# List of numerical features (update with your actual columns)
numerical_features = df.select_dtypes(include=['float64', 'int64']).columns.tolist()

# Remove outliers
df_cleaned, outliers_z = remove_outliers(df, numerical_features)

# Print the shape of the cleaned DataFrame
print(f"Original DataFrame shape: {df.shape}")
print(f"Cleaned DataFrame shape after Z-score filtering: {df_cleaned.shape}")

# Save the cleaned dataset as a CSV file
output_file = "outlier_remove_zscore.csv"
df_cleaned.to_csv(output_file, index=False)

# Optionally, inspect the cleaned data
print(df_cleaned[numerical_features].head())  # Check the first few rows after cleaning with Z-scores

# Print the file path where the cleaned dataset was saved
print(f"Cleaned data after Z-score filtering saved as: {output_file}")

# Optional: If you want to inspect the number of outliers in each column
outliers_count = outliers_z.sum()
print("Number of outliers detected in each feature:")
print(outliers_count)

Original DataFrame shape: (41188, 21)
Cleaned DataFrame shape after Z-score filtering: (37314, 21)
   age  duration  campaign  pdays  previous  emp.var.rate  cons.price.idx  \
0   56       261         1    999         0           1.1          93.994
1   57       149         1    999         0           1.1          93.994
2   37       226         1    999         0           1.1          93.994
3   40       151         1    999         0           1.1          93.994
4   56       307         1    999         0           1.1          93.994

   cons.conf.idx  euribor3m  nr.employed
0          -36.4      4.857       5191.0
1          -36.4      4.857       5191.0
2          -36.4      4.857       5191.0
3          -36.4      4.857       5191.0
4          -36.4      4.857       5191.0
Cleaned data after Z-score filtering saved as: outlier_remove_zscore.csv
Number of outliers detected in each feature:
age                369
duration           861
campaign           869
pdays             1515
previous          1064
emp.var.rate         0
cons.price.idx       0
cons.conf.idx        0
euribor3m            0
nr.employed          0
dtype: int64

# Handle Imbalanced dataset and apply one hot encoding

In [8]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from imblearn.over_sampling import SMOTE
from collections import Counter

# Step 1: Load the cleaned dataset (after outlier removal)
df_cleaned = pd.read_csv("/content/outlier_remove_zscore.csv")

# Step 2: Check the class distribution before handling class imbalance
print("Class Distribution Before Handling:\n", df_cleaned['y'].value_counts())

# Step 3: Replace or remove infinite values in the dataset
df_cleaned.replace([np.inf, -np.inf], np.nan, inplace=True)  # Replace inf/-inf with NaN
df_cleaned.dropna(inplace=True)  # Drop rows with NaN (if any remain)

# Step 4: Convert True/False values to 1/0 (for the entire DataFrame)
df_cleaned = df_cleaned.applymap(lambda x: int(x) if isinstance(x, bool) else x)

# Step 5: Convert categorical variables to numerical using One-Hot Encoding (for features)
df_cleaned = pd.get_dummies(df_cleaned, drop_first=True)

# Step 6: Separate features (X) and target (y)
X = df_cleaned.drop(columns=['y_yes'])  # Drop the 'y_yes' column after One-Hot Encoding
y = df_cleaned['y_yes'].astype(int)  # Ensure target column is converted to integers

# Option: Rename the target column back to 'y' if you prefer to keep this name
df_cleaned.rename(columns={'y_yes': 'y'}, inplace=True)

# Step 7: Convert y to integer type to ensure 0/1 representation
y = y.astype(int)

# Step 8: Apply SMOTE to balance the dataset (oversample the minority class)
smote = SMOTE(random_state=42)
X_smote, y_smote = smote.fit_resample(X, y)

# Step 9: Check the class distribution after SMOTE
print("Class Distribution After SMOTE:\n", Counter(y_smote))

# Step 10: Save the balanced dataset as a CSV
balanced_dataset = pd.concat([pd.DataFrame(X_smote, columns=X.columns), pd.Series(y_smote, name='y')], axis=1)
output_path = "processed_Dataset.csv"
balanced_dataset.to_csv(output_path, index=False)
print(f"Balanced dataset saved to {output_path}")

Class Distribution Before Handling:
 y
no     34346
yes     2968
Name: count, dtype: int64
Class Distribution After SMOTE:
 Counter({0: 34346, 1: 34346})
Balanced dataset saved to processed_Dataset.csv

# Preprocessed Dataset

In [9]:
# Identify boolean columns in the dataframe
bool_columns = df_cleaned.select_dtypes(include='bool').columns

# Convert boolean columns to integers (1 for True, 0 for False)
df_cleaned[bool_columns] = df_cleaned[bool_columns].astype(int)

# Verify the change
print(df_cleaned[bool_columns].dtypes)

# Save the cleaned and processed dataset to a CSV file
output_path = "Final_Processed_Data.csv"
df_cleaned.to_csv(output_path, index=False)

print(f"Processed dataset saved to {output_path}")

job_blue-collar                  int64
job_entrepreneur                 int64
job_housemaid                    int64
job_management                   int64
job_retired                      int64
job_self-employed                int64
job_services                     int64
job_student                      int64
job_technician                   int64
job_unemployed                   int64
job_unknown                      int64
marital_married                  int64
marital_single                   int64
marital_unknown                  int64
education_basic.6y               int64
education_basic.9y               int64
education_high.school            int64
education_illiterate             int64
education_professional.course    int64
education_university.degree      int64
education_unknown                int64
default_unknown                  int64
default_yes                      int64
housing_unknown                  int64
housing_yes                      int64
loan_unknown                     int64
loan_yes                         int64
contact_telephone                int64
month_aug                        int64
month_dec                        int64
month_jul                        int64
month_jun                        int64
month_mar                        int64
month_may                        int64
month_nov                        int64
month_oct                        int64
month_sep                        int64
day_of_week_mon                  int64
day_of_week_thu                  int64
day_of_week_tue                  int64
day_of_week_wed                  int64
poutcome_nonexistent             int64
y                                int64
dtype: object
Processed dataset saved to Final_Processed_Data.csv